"""add deal URL fields

Revision ID: 6d0337af61be
Revises: 827ffd208b71
Create Date: 2026-07-29 00:31:49.702582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0337af61be'
down_revision = '827ffd208b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('deal_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_deals', schema=None) as batch_op:
        batch_op.drop_column('deal_url')
        batch_op.drop_column('business_url')

    # ### end Alembic commands ###
