"""create student deals table

Revision ID: 827ffd208b71
Revises: c1e32f1cc7c8
Create Date: 2026-07-28 22:04:45.320034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827ffd208b71'
down_revision = 'c1e32f1cc7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('food', 'coffee', 'shopping', 'services', 'entertainment', 'wellness', 'other', name='deal_category', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'paused', 'expired', name='deal_status', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('business', 'instead', 'community', name='deal_source', native_enum=False), nullable=False),
    sa.Column('discount_text', sa.String(length=80), nullable=False),
    sa.Column('location_name', sa.String(length=160), nullable=False),
    sa.Column('redemption_instructions', sa.Text(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('promo_code', sa.String(length=80), nullable=True),
    sa.Column('business_email', sa.String(length=255), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_deals_business_email'), ['business_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_deals_business_name'), ['business_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_deals_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_deals_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_deals_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_deals_status'))
        batch_op.drop_index(batch_op.f('ix_student_deals_expires_at'))
        batch_op.drop_index(batch_op.f('ix_student_deals_category'))
        batch_op.drop_index(batch_op.f('ix_student_deals_business_name'))
        batch_op.drop_index(batch_op.f('ix_student_deals_business_email'))

    op.drop_table('student_deals')
    # ### end Alembic commands ###
